version: 0.2

phases:
  install:
    commands:
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
  build:
    commands:
      - docker login -u fanhousanbu -p $DOCKER_SECRET
      - docker build -t $REPOSITORY_URI/devops:$CODEBUILD_START_TIME .
      - aws ecr-public get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - docker push $REPOSITORY_URI/devops:$CODEBUILD_START_TIME
  post_build:
    commands:
      #- sed -i -e "s/\($REPOSITORY_URI\/devops[^:]*:\)[a-z0-9_-]*/\1$CODEBUILD_START_TIME/g" hello-k8s.yml
      - sed -i -e "s/\(public.ecr.aws/f0e5p9a6/devops\/[^:]*:\)[a-z0-9_-]*/\1$CODEBUILD_START_TIME/g" hello-k8s.yml
      - aws configure set access_key $ACCESS_KEY
      - aws configure set secret_key $ACCESS_SECRET
      - aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME
      - kubectl apply -f hello-k8s.yml
