---
version: 0.2
phases:
  install:
    commands:
      - curl -sS -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-07-26/bin/linux/amd64/aws-iam-authenticator
      - curl -sS -o kubectl https://amazon-eks.s3-us-west-2.amazonaws.com/1.14.6/2019-08-22/bin/linux/amd64/kubectl
      - chmod +x ./kubectl ./aws-iam-authenticator
      - export PATH=$PWD/:$PATH
      - apt-get update && apt-get -y install jq python3-pip python3-dev && pip3 install --upgrade awscli
  pre_build:
      commands:
        - TAG="$REPOSITORY_NAME.$REPOSITORY_BRANCH.$ENVIRONMENT_NAME.$(date +%Y-%m-%d.%H.%M.%S).$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
        - sed -i 's@CONTAINER_IMAGE@'"$REPOSITORY_URI:latest"'@' hello-k8s.yml
        - cat hello-k8s.yml
        - $(aws ecr get-login --no-include-email)
        - export KUBECONFIG=$HOME/.kube/config
  build:
    commands:
      - docker login -u fanhousanbu -p xcworld
      - docker build --tag $REPOSITORY_URI:latest .

  post_build:
    commands:
      - echo 'eyJwYXlsb2FkIjoidzVJWDhpbTNTTzRjMXRkSTZiVVNnSzkvUXUxejhhRXBUVU82alFYK1Y1WGQ3VjRwTWI0bEJmMjNVWldnVkJjcEJLUEZmUWEzck0xelo0bW5iTEl2SXB4b2hGTGU1TDk3WjhJaVRJa2p6bFJnVXRTa2NjTTFtOXNXQ09iYkRmY3A1bHB5UllYUzM5WEJmeVlnbVdaT09jRDl3K25NWmEvb21vM0pGZjFqZGRVRFprOGphc1NrU0dVUnZ1aXBuNXdlNWw4VmVxck1uOFp3UXRrOHZFZitJRnBjbWxVWitaQUZJcW5BdDlxa20yWWJRT3lUbGZodDBMZG8rMkxMVTJKVmFOa05CUkVvUUZZYUZHakpDK1NZMTdQNTVQSkt1OXZRd3VEcEltMStlYXF2MkREbnJLamJuSFVadEdaRGZwOHRNZWNVUFJGSXFUb3hjWGNNcXhTVElEYzFtN1psMDRsK2FBSkNBZEtiZThlUHRTdURqODlsTzlsOTNINjJJV1JidlVURDZZcm03NThucXBtTlRST09hYlpFdnAvSEYwdE1uNXQyLzFNK1F2NnpOQXptOTcvaGR2NFM1aS96Sll4bVNHRjlXd1Bna1BEdXc2UzZOTXF3ZmJhamxTZU5BN0FzZGZGMHpFMlQ5Qm94cXhkUUczUnFZWU9DbTVDV1NQU1NZZnFXMjlHaG1uS09Qc055UUdHVVhFK09KMUYzdzZCTlFuYkQ2VlNieDBsdmpqdHRWSWN2QVZnSVNodHp5a3UvTVBIekVhVVQ3LzRULzRtWGZ0MWJJZHE5cGx3R1NuelVHam9MaEpmeUJBdW41bnAzOVJhMFN6NDlPaWZ5VWpLMVl6dzhqWUtPUDBSV3ZKYmJNa2ZnL0NwZDQ3UHlxK051bHlJbnFhVGh3aGlvVldoY3o4N0N6NmQxajgvUEVTaE9jRHZzN3ZlOVhmR2Y1eE1uRjEzZjQ2U2R6ek9Ba2Y4VDVtSnVTZ28zb2s5NkpWTy81UFYrbWhCY0lETE04YWpMY2h1K1orb2QvQzFOUFFWRkZLWlpVVHhBb3gxc2xtWUlwR25ZeTJTK3d4ZGIvTUpSQXh3dUxuN0J2bnIxT0Zqa2VIQ1o2WjVUbjF0ZWlOWFUvNUYzV0libzBUekYyM0IxdWhoVGRCUVFBNS8xeUg0ME9HeTRUdERxSTN1WmRwSVIvTG5MbnRhZkQydFZtTG1tdjB2d0FYRkNsZEswVnQrcmpCZVVhN1FLUFp4VmcycS9PQncrQmpMS3ZCczZPUG5jOWQ1ZHhWclUzek9LcnR3dDZEcTRiRFU5ejhyVU5XUlJkYm9qZVRXK0U0RDhrUkx0UnJMbU1pU1RhZ2VnNVk2RHBzelcrMlc4SzFJcE9wYTdaYWtwdTZQRnBmc3IiLCJkYXRha2V5IjoiQVFJQkFIaldYdzZaU3NlQ2RBbCtOb2RGWXdmL2hSbXNMQTJuZ2E1QkJmdmJrUG5PYndGYml2aHI4eXdGcjF3SmFzdWJqVHlCQUFBQWZqQjhCZ2txaGtpRzl3MEJCd2FnYnpCdEFnRUFNR2dHQ1NxR1NJYjNEUUVIQVRBZUJnbGdoa2dCWlFNRUFTNHdFUVFNdmh1S25SbWlzUmVUcWZ4REFnRVFnRHV2cVdrM0lNZVdNd1dIUU5OZUtoaEtuQW5jejFTZE5rK1J0QU42cVFpRmNWS3QvQlRtY0ZiOWE0TlBRV2YxOEp2WmVJdmdHVmFUSHlqbjVRPT0iLCJ2ZXJzaW9uIjoiMiIsInR5cGUiOiJEQVRBX0tFWSIsImV4cGlyYXRpb24iOjE2ODg0MzEyNDh9' | docker login --username AWS --password-stdin public.ecr.aws/f0e5p9a6
      - docker push $REPOSITORY_URI:latest
      - CREDENTIALS=$(aws sts assume-role --role-arn arn:aws:iam::008758743766:role/codebuild-test-app-build-role --role-session-name codebuild-kubectl --duration-seconds 900)
      - export AWS_ACCESS_KEY_ID="$(echo ${CREDENTIALS} | jq -r '.Credentials.AccessKeyId')"
      - export AWS_SECRET_ACCESS_KEY="$(echo ${CREDENTIALS} | jq -r '.Credentials.SecretAccessKey')"
      - export AWS_SESSION_TOKEN="$(echo ${CREDENTIALS} | jq -r '.Credentials.SessionToken')"
      - export AWS_EXPIRATION=$(echo ${CREDENTIALS} | jq -r '.Credentials.Expiration')
      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME
      - kubectl apply -f hello-k8s.yml
      - printf '[{"name":"hello-k8s","imageUri":"%s"}]' $REPOSITORY_URI:latest > build.json
artifacts:
  files: build.json
